import User from '#models/user'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    await User.createMany([
      {
        firstname: 'Jean-Marc',
        lastname: 'Panacloc',
        niss: '80.08.24-124.89',
        nickname: 'J&M',
        email: 'jm@test.com',
        password: 'ventriloque',
        address: {
          street: 'rue du test',
          number: '4',
          city: 'Tournai',
          zip_code: 7500
        },
        userType: 'admin'
      },
      {
        firstname: 'Bender',
        lastname: 'Rodriguez',
        niss: '82.09.14-123.87',
        nickname: 'Le tordeur',
        email: 'bender@test.com',
        password: 'futurama',
        address: {
          street: 'rue du test',
          number: '1',
          city: 'Tournai',
          zip_code: 7500       
        },
      },
      {
        firstname: 'Nicky',
        lastname: 'Larson',
        niss: '78.12.04-114.29',
        nickname: 'Ryo',
        email: 'nl@test.com',
        password: 'cityhunter',
        address: {
          street: 'rue du test',
          number: '7c',
          city: 'Leuze',
          zip_code: 7900,
        },
      },
      {
        firstname: 'Lara',
        lastname: 'Croft',
        niss: '64.11.02-104.69',
        nickname: 'LC',
        email: 'lara@test.com',
        password: 'motdepasse',
        address: {
          street: 'rue du test',
          number: '7c',
          city: 'Mons',
          zip_code: 7000,
        },
      },
      {
        firstname: 'Leia',
        lastname: 'Organa',
        niss: '48.02.12-112.29',
        nickname: 'Princesse L',
        email: 'leia@test.com',
        password: 'princesse',
        address: {
          street: 'rue du test',
          number: '42',
          city: 'Péruwelz',
          zip_code: 7600,
        },
      },
      {
        firstname: 'Tony',
        lastname: 'Stark',
        niss: '48.02.13-112.29',
        nickname: 'IronDick',
        email: 'tony@test.com',
        password: 'ironman1',
        address: {
          street: 'rue du test',
          number: '12',
          city: 'Péruwelz',
          zip_code: 7600,
        },
      },
      {
        firstname: 'Natasha',
        lastname: 'Romanoff',
        niss: '48.02.14-112.29',
        nickname: 'BlackDildo',
        email: 'nr@test.com',
        password: 'blackwidow',
        address: {
          street: 'rue du test',
          number: '21',
          city: 'Péruwelz',
          zip_code: 7600,
        },
      },
      {
        firstname: 'Jean',
        lastname: 'Grey',
        niss: '48.02.15-112.29',
        nickname: 'PhoeniXxX',
        email: 'jg@test.com',
        password: 'phoenix1',
        address: {
          street: 'rue du test',
          number: '69',
          city: 'Péruwelz',
          zip_code: 7600,
        },
      },
      {
        firstname: 'Ororo',
        lastname: 'Munroe',
        niss: '48.04.12-112.29',
        nickname: 'Partouzeuse',
        email: 'om@test.com',
        password: 'tornade1',
        address: {
          street: 'rue du test',
          number: '74',
          city: 'Ath',
          zip_code: 7800,
        },
      },
      {
        firstname: 'Diana',
        lastname: 'Prince',
        niss: '48.12.12-112.29',
        nickname: 'Dominatrix',
        email: 'dp@test.com',
        password: 'wonderwoman',
        address: {
          street: 'rue du test',
          number: '78',
          city: 'Ath',
          zip_code: 7800,
        },
      },
      {
        firstname: 'Barbara',
        lastname: 'Gordon',
        niss: '48.06.12-112.29',
        nickname: 'boobsgirl',
        email: 'bg@test.com',
        password: 'batgirl1',
        address: {
          street: 'rue du test',
          number: '114',
          city: 'Charleroi',
          zip_code: 6000,
        },
      },
      {
        firstname: 'Selina',
        lastname: 'Kyle',
        niss: '88.10.12-112.29',
        nickname: 'ChatteWoman',
        email: 'sk@test.com',
        password: 'catwoman',
        address: {
          street: 'rue du test',
          number: '88',
          city: 'Namur',
          zip_code: 5000,
        },
      },
      {
        firstname: 'Jennifer',
        lastname: 'Walters',
        niss: '48.07.13-112.29',
        nickname: 'Fantaskfist',
        email: 'jw@test.com',
        password: 'shehulk1',
        address: {
          street: 'rue du test',
          number: '689',
          city: 'Péruwelz',
          zip_code: 7600,
        },
      },
      {
        firstname: 'Pamela',
        lastname: 'Isley',
        niss: '78.08.12-112.29',
        nickname: 'PlugOnIvy',
        email: 'pi@test.com',
        password: 'poisonivy',
        address: {
          street: 'rue du test',
          number: '12A',
          city: 'Liège',
          zip_code: 4000,
        },
      },
      {
        firstname: 'Kara',
        lastname: 'Zor-El',
        niss: '68.02.12-112.29',
        nickname: 'VerySuperGirl',
        email: 'kze@test.com',
        password: 'krypton1',
        address: {
          street: 'rue du test',
          number: '879',
          city: 'Burxelles',
          zip_code: 1000,
        },
      },
      {
        firstname: 'Thor',
        lastname: 'Odinson',
        niss: '28.02.12-112.29',
        nickname: 'Le ctrl de Foutre',
        email: 'thoro@test.com',
        password: 'mjollnir',
        address: {
          street: 'rue du test',
          number: '1C',
          city: 'Gand',
          zip_code: 9000,
        },
      },
      {
        firstname: 'Steve',
        lastname: 'Amissi',
        niss: '98.02.12-112.29',
        nickname: 'Captain Braquemard',
        email: 'steva@test.com',
        password: 'amissi01',
        address: {
          street: 'rue du test',
          number: '8B',
          city: 'Tournai',
          zip_code: 7500,
        },
      },
      {
        firstname: 'Amaury',
        lastname: 'Meersman',
        niss: '79.03.12-112.29',
        nickname: 'Le pervers',
        email: 'am@test.com',
        password: 'amaury00',
        address: {
          street: 'rue du test',
          number: '412',
          city: 'Dottignies',
          zip_code: 7711,
        },
      },
      {
        firstname: 'James',
        lastname: 'Howlett',
        niss: '38.09.12-112.29',
        nickname: 'Logan',
        email: 'jh@test.com',
        password: 'wolverine',
        address: {
          street: 'rue du test',
          number: '2C',
          city: 'Mouscron',
          zip_code: 7700,
        },
      },
      {
        firstname: 'Bruce',
        lastname: 'Wayne',
        niss: '88.04.14-112.29',
        nickname: 'DickMan',
        email: 'bw@test.com',
        password: 'batman01',
        address: {
          street: 'rue du test',
          number: '412',
          city: 'Anvers',
          zip_code: 2000,
        },
      },
    ])
  }
}
