import UserProfile from '#models/user_profile'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

export default class extends BaseSeeder {
  async run() {
    await UserProfile.createMany([
      {
        userId: 1,
        genre: 'homme',
        orientation: 'hétéro',
        size: 100,
        weight: 25,
        penis_size: 4,
        hairColor: 'roux',
        eyeColor: 'bleu',
      },
      {
        userId: 2,
        genre: 'robot',
        orientation: 'plug & play',
        size: 180,
        weight: 85,
        hairColor: 'gris',
        eyeColor: 'noir',
      },
      {
        userId: 3,
        genre: 'homme',
        orientation: 'hétéro',
        size: 185,
        weight: 80,
        penis_size: 18,
        hairColor: 'noir',
        eyeColor: 'bleu',
      },
      {
        userId: 4,
        genre: 'femme',
        orientation: 'homo',
        size: 160,
        weight: 50,
        bra_cup: 'bonnet C',
        hairColor: 'auburn',
        eyeColor: 'vert',
      },
      {
        userId: 5,
        genre: 'femme',
        orientation: 'hétéro',
        size: 162,
        weight: 48,
        bra_cup: 'bonnet C',
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 6,
        genre: 'homme',
        orientation: 'hétéro',
        size: 184,
        weight: 79,
        penis_size: 17,
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 7,
        genre: 'femme',
        orientation: 'hétéro',
        size: 163,
        weight: 48,
        bra_cup: 'bonnet C',
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 8,
        genre: 'femme',
        orientation: 'hétéro',
        size: 165,
        weight: 48,
        bra_cup: 'bonnet C',
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 9,
        genre: 'femme',
        orientation: 'hétéro',
        size: 172,
        weight: 58,
        bra_cup: 'bonnet C',
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 10,
        genre: 'femme',
        orientation: 'homo',
        size: 158,
        weight: 48,
        bra_cup: 'bonnet C',
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 11,
        genre: 'femme',
        orientation: 'hétéro',
        size: 155,
        weight: 48,
        bra_cup: 'bonnet C',
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 12,
        genre: 'femme',
        orientation: 'pas difficile',
        size: 162,
        weight: 48,
        bra_cup: 'bonnet C',
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 13,
        genre: 'femme',
        orientation: 'hétéro',
        size: 157,
        weight: 48,
        bra_cup: 'bonnet C',
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 14,
        genre: 'femme',
        orientation: 'hétéro',
        size: 153,
        weight: 44,
        bra_cup: 'bonnet C',
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 15,
        genre: 'femme',
        orientation: 'hétéro',
        size: 167,
        weight: 58,
        bra_cup: 'bonnet C',
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 16,
        genre: 'homme',
        orientation: 'hétéro',
        size: 200,
        weight: 89,
        penis_size: 22,
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 17,
        genre: 'homme',
        orientation: 'hétéro',
        size: 187,
        weight: 84,
        penis_size: 15,
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 18,
        genre: 'homme',
        orientation: 'hétéro',
        size: 155,
        weight: 55,
        penis_size: 14,
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 19,
        genre: 'homme',
        orientation: 'pas difficile',
        size: 187,
        weight: 87,
        penis_size: 17,
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
      {
        userId: 20,
        genre: 'transformers',
        orientation: 'pas difficile',
        size: 191,
        weight: 87,
        penis_size: 22,
        hairColor: 'auburn',
        eyeColor: 'brun',
      },
    ])
  }
}
